---
title: "Programming in Base R"
format: html
editor: visual
---

## Task 1: Basic Vector Practice

Enter in blood pressure data and assign names.

```{r}
pre_trt <- c(120, 151, 125, 126, 115, 132, 132, 129, 134, 139, 
             127, 122, 127, 135, 133, 128, 147, 138, 140, 132)

names(pre_trt) <- paste("Subject", 1:20, sep = "_")

post_trt <- c(127, 145, 135, 122, 115, 122, 123, 126, 126, 129, 
              132, 146, 120, 114, 121, 120, 128, 120, 133, 115)

names(post_trt) <- paste("Subject", 1:20, sep = "_")
```

Calculate change in blood pressure and averages.

```{r}
# Change in blood pressure from pre treatment to post treatment for each subject.
diff <- pre_trt - post_trt
diff

# Average decrease in blood pressure across all patients.
avg_diff <- mean(diff)
avg_diff

# Which patients experienced a decrease in blood pressure after treatment.
pos_index <- which(diff > 0)
pos_index

# Get those patients blood pressure difference.
positive_patients <- diff[pos_index]
positive_patients

# Calculate the average decrease in blood pressure for positive patients.
pos_avg_diff <- mean(positive_patients)
pos_avg_diff
```

## Task 2: Basic Data Frame Practice

Create a data frame from the previous example.

```{r}
bp_df <- data.frame(patient = names(pre_trt), 
                    pre_bp = pre_trt,
                    post_bp = post_trt,
                    diff_bp = diff,
                    row.names = NULL)
bp_df
```

```{r}
# Return only rows of the data frame where the diff_bp is negative.
neg_bp_df <- bp_df[bp_df$diff_bp < 0,]
neg_bp_df
```

```{r}
# Add a column for subjects that has true for post_bp less than 120.
bp_df$low_bp <- bp_df$post_bp < 120
bp_df$low_bp
```

```{r}
# Print the data frame nicely.
knitr::kable(bp_df)
```
